"""Concept viewer component for Sensei.

This module provides display for lesson content including:
- Markdown rendering (with automatic code syntax highlighting)
- Navigation controls
- Loading states

The lesson content is expected to be a complete markdown document
generated by the Teaching Crew, which includes explanations, code
examples, and key takeaways all in one unified format.
"""

from typing import Any, Callable

import streamlit as st


def render_concept(title: str, content: str) -> None:
    """Render concept content with markdown.
    
    The content should be a complete markdown lesson generated by
    the Teaching Crew, which includes explanations, code examples,
    and key takeaways. Streamlit automatically handles code block
    syntax highlighting.
    
    Args:
        title: The concept title.
        content: Complete lesson content in markdown format.
    
    Example:
        ```python
        render_concept(
            title="Thread Blocks",
            content="A **thread block** is a group of threads...\\n\\n```python\\nprint('Hello')\\n```",
        )
        ```
    """
    # Concept title
    st.markdown(f"## {title}")
    
    # Main content (markdown) - Streamlit auto-highlights code blocks
    if content:
        st.markdown(content)
    else:
        _render_empty_content()


def render_concept_with_navigation(
    title: str,
    content: str,
    concept_idx: int,
    total_concepts: int,
    module_title: str | None = None,
    on_previous: Callable[[], None] | None = None,
    on_next: Callable[[], None] | None = None,
    can_go_previous: bool = True,
    can_go_next: bool = True,
) -> None:
    """Render concept with previous/next navigation controls.
    
    Args:
        title: The concept title.
        content: Complete lesson content in markdown.
        concept_idx: Current concept index (0-based).
        total_concepts: Total number of concepts in module.
        module_title: Optional module title to display.
        on_previous: Callback when Previous button is clicked.
        on_next: Callback when Next button is clicked.
        can_go_previous: Whether previous navigation is available.
        can_go_next: Whether next navigation is available.
    """
    # Module context
    if module_title:
        st.caption(f"📚 {module_title}")
    
    # Progress indicator
    _render_progress_dots(concept_idx, total_concepts)
    
    st.markdown("---")
    
    # Main concept content
    render_concept(title, content)
    
    st.markdown("---")
    
    # Navigation buttons
    col1, col2, col3 = st.columns([1, 2, 1])
    
    with col1:
        if can_go_previous and concept_idx > 0:
            if st.button("◀ Previous", key="prev_concept", use_container_width=True):
                if on_previous:
                    on_previous()
        else:
            st.empty()
    
    with col2:
        st.markdown(
            f"<p style='text-align: center; color: #6c757d;'>Concept {concept_idx + 1} of {total_concepts}</p>",
            unsafe_allow_html=True,
        )
    
    with col3:
        if can_go_next and concept_idx < total_concepts - 1:
            if st.button("Next ▶", key="next_concept", use_container_width=True, type="primary"):
                if on_next:
                    on_next()
        elif concept_idx >= total_concepts - 1:
            # Last concept - show module complete indicator
            st.success("✓ Module Complete!")
        else:
            st.empty()


def render_lesson_header(
    course_title: str,
    module_title: str,
    module_idx: int,
    total_modules: int,
) -> None:
    """Render the lesson page header with course and module info.
    
    Args:
        course_title: The course name.
        module_title: The current module name.
        module_idx: Current module index (0-based).
        total_modules: Total number of modules in course.
    """
    st.markdown(f"# 📚 {course_title}")
    st.markdown(f"**{module_title}** (Module {module_idx + 1} of {total_modules})")


def render_loading_state(
    message: str = "Generating lesson content...",
    icon: str = "🥋",
    estimated_time: str | None = None,
    tips: list[str] | None = None,
    show_spinner: bool = True,
) -> None:
    """Render an enhanced loading state while AI content is being generated.
    
    Provides a visually appealing loading experience with optional
    estimated wait time and educational tips.
    
    Args:
        message: Main loading message to display.
        icon: Emoji icon to show (default: 🥋 Sensei).
        estimated_time: Optional estimated wait time (e.g., "30-60 seconds").
        tips: Optional list of tips to display while waiting.
        show_spinner: Whether to show the spinning indicator.
    
    Example:
        ```python
        render_loading_state(
            message="Teaching Crew is preparing your lesson...",
            icon="📖",
            estimated_time="30-60 seconds",
            tips=["Great time to stretch!", "AI is analyzing the best way to explain this"],
        )
        ```
    """
    with st.container():
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            # Main loading card with animated gradient
            st.markdown(
                f"""
                <style>
                @keyframes pulse {{
                    0%, 100% {{ opacity: 1; }}
                    50% {{ opacity: 0.7; }}
                }}
                .loading-card {{
                    text-align: center;
                    padding: 2.5rem;
                    background: linear-gradient(135deg, #e8f4fd 0%, #f0f7ff 100%);
                    border: 1px solid #b8daff;
                    border-radius: 15px;
                    margin: 2rem 0;
                }}
                .loading-icon {{
                    font-size: 3.5rem;
                    margin-bottom: 1rem;
                    animation: pulse 2s ease-in-out infinite;
                }}
                .loading-message {{
                    color: #004085;
                    font-size: 1.15rem;
                    font-weight: 500;
                    margin: 0.5rem 0;
                }}
                .loading-estimate {{
                    color: #6c757d;
                    font-size: 0.9rem;
                    margin-top: 0.5rem;
                }}
                </style>
                <div class="loading-card">
                    <div class="loading-icon">{icon}</div>
                    <p class="loading-message">{message}</p>
                    {f'<p class="loading-estimate">⏱️ Usually takes {estimated_time}</p>' if estimated_time else ''}
                </div>
                """,
                unsafe_allow_html=True,
            )
            
            # Show spinner
            if show_spinner:
                st.spinner("Please wait...")
            
            # Show tips if provided
            if tips:
                import random
                tip = random.choice(tips)
                st.markdown(
                    f"""
                    <div style="
                        text-align: center;
                        padding: 1rem;
                        background: #fff3cd;
                        border: 1px solid #ffc107;
                        border-radius: 8px;
                        margin-top: 1rem;
                    ">
                        <span style="font-size: 1rem;">💡</span>
                        <span style="color: #856404; font-size: 0.9rem;">{tip}</span>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )


def _render_progress_dots(current: int, total: int) -> None:
    """Render progress indicator as filled/empty dots.
    
    Args:
        current: Current position (0-based).
        total: Total items.
    """
    dots = []
    for i in range(total):
        if i < current:
            dots.append("●")  # Completed
        elif i == current:
            dots.append("◉")  # Current
        else:
            dots.append("○")  # Not reached
    
    dots_str = " ".join(dots)
    st.markdown(
        f"<p style='text-align: center; letter-spacing: 0.3rem; color: #007bff;'>{dots_str}</p>",
        unsafe_allow_html=True,
    )


def _render_empty_content() -> None:
    """Render placeholder when content is empty."""
    st.markdown(
        """
        <div style="
            text-align: center;
            padding: 2rem;
            background: #f8f9fa;
            border-radius: 8px;
            color: #6c757d;
        ">
            <span style="font-size: 2rem;">📝</span>
            <p>Content is being generated...</p>
        </div>
        """,
        unsafe_allow_html=True,
    )


def render_concept_card(
    concept: dict[str, Any],
    on_select: Callable[[str], None] | None = None,
    is_current: bool = False,
    is_completed: bool = False,
) -> None:
    """Render a concept as a clickable card.
    
    Used in module overview to show concept list.
    
    Args:
        concept: Concept data with id, title, description.
        on_select: Callback when concept is selected.
        is_current: Whether this is the current concept.
        is_completed: Whether the concept is completed.
    """
    concept_id = concept.get("id", "")
    title = concept.get("title", "Untitled")
    description = concept.get("description", "")[:100]
    
    # Status icon
    if is_completed:
        icon = "✅"
        border_color = "#28a745"
    elif is_current:
        icon = "▶"
        border_color = "#007bff"
    else:
        icon = "○"
        border_color = "#dee2e6"
    
    st.markdown(
        f"""
        <div style="
            border: 2px solid {border_color};
            border-radius: 8px;
            padding: 1rem;
            margin: 0.5rem 0;
            cursor: pointer;
        ">
            <strong>{icon} {title}</strong>
            <p style="color: #6c757d; font-size: 0.9rem; margin: 0.5rem 0 0 0;">{description}</p>
        </div>
        """,
        unsafe_allow_html=True,
    )
    
    if st.button(
        "Select" if not is_current else "Currently Learning",
        key=f"select_concept_{concept_id}",
        disabled=is_current,
    ):
        if on_select and not is_current:
            on_select(concept_id)
